# Generated by Django 3.2.7 on 2021-12-22 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboxmessage",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message",
                to="inbox.inboxchannel",
            ),
        ),
    ]
