# Generated by Django 3.2.7 on 2021-12-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0002_alter_inboxmessage_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxchannel",
            name="encounter_reason",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
