# Generated by Django 3.2.7 on 2021-12-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0003_inboxchannel_encounter_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboxmessage",
            name="uploaded_file",
            field=models.FileField(
                blank=True, null=True, upload_to="conversation_upload_file"
            ),
        ),
        migrations.AddField(
            model_name="inboxmessage",
            name="uploaded_file_mimetype",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
