from django.urls import path
from .views import (
    AddEncounters,
    AllEncounters,
    AssessmentDiagnosisUpdateView,
    AssessmentDiagnosisView,
    AssessmentDiagnosisByEncounterIDView,
    ICDsView,
    PlanOfCareUpdateView,
    PlanOfCareView,
    PlanOfCareByEncounterIDView,
    PatientEncountersView,
    PatientSocialHistoryUpdateView,
    PatientSocialHistoryView,
    PatientSocialHistoryByEncounterIDView
)

urlpatterns = [
    path("encounters/<uuid:patient_uuid>/", AllEncounters.as_view(), name="patient-encounter-list"),
    path("encounters/add", AddEncounters.as_view(), name="encounter-add"),
    path(
        "patient-encounters/<uuid:pk>/",
        PatientEncountersView.as_view(),
        name="patient-encounter-list",
    ),
    path(
        "encounters/assessments/<uuid:patient_encounter_uuid>/",
        AssessmentDiagnosisByEncounterIDView.as_view(),
        name="patient-encounter-assessments",
    ),
    path(
        "encounters/assessments/",
        AssessmentDiagnosisView.as_view(),
        name="patient-encounter-assessments",
    ),
    path(
        "encounters/plan-of-care/",
        PlanOfCareView.as_view(),
        name="patient-encounter-plan-of-care",
    ),
    path(
        "encounters/plan-of-care/<uuid:patient_encounter_uuid>/",
        PlanOfCareByEncounterIDView.as_view(),
        name="patient-encounter-plan-of-care",
    ),
    path(
        "encounters/assessments/<uuid:pk>/",
        AssessmentDiagnosisUpdateView.as_view(),
        name="patient-encounter-assessments-update",
    ),
    path(
        "encounters/plan-of-care/<uuid:pk>/",
        PlanOfCareUpdateView.as_view(),
        name="patient-encounter-plan-of-care-update",
    ),
    path(
        "encounters/social-history/",
        PatientSocialHistoryView.as_view(),
        name="patient-social-history",
    ),
    path(
        "encounters/social-history/<uuid:patient_encounter_uuid>/",
        PatientSocialHistoryByEncounterIDView.as_view(),
        name="patient-social-history",
    ),
    path(
        "encounters/social-history/<uuid:pk>/",
        PatientSocialHistoryUpdateView.as_view(),
        name="patient-social-history-update",
    ),
    path(
        "encounters/icd/<icd_description>/",
        ICDsView.as_view(),
        name="icd-code-list",
    ),
]
