# Generated by Django 3.2.7 on 2021-12-26 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubscriptionHistoryPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.CharField(max_length=30)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionhistory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
