# Generated by Django 3.2.7 on 2021-12-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20211226_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='subscription_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='subscription_start',
            field=models.DateField(null=True),
        ),
    ]
