# Generated by Django 3.2.7 on 2021-12-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscriptionhistory_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='paid',
        ),
    ]
