# Generated by Django 3.2.7 on 2021-12-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_subscriptionhistory_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='extra_gateway_values',
            field=models.CharField(default='', max_length=100),
        ),
    ]
