# Generated by Django 3.2.7 on 2021-12-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20211227_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionhistory',
            old_name='cancelled',
            new_name='paused',
        ),
    ]
