# Generated by Django 3.2.7 on 2021-11-24 08:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0040_auto_20211108_1054"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("number_of_patients", models.IntegerField(default=0)),
                ("payment_status", models.BooleanField(default=False)),
                ("transaction_id", models.CharField(max_length=100, null=True)),
                ("patient_status", models.CharField(max_length=50, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_appointment",
                        to="user.doctorinfo",
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_appointment",
                        to="user.patientinfo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
