# Generated by Django 3.2.7 on 2022-01-06 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_merge_20220105_1539'),
        ('accounting', '0002_payment_appointment'),
        ('appointment', '0002_alter_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentt', to='accounting.payment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.doctorservice'),
            preserve_default=False,
        ),
    ]
