# Generated by Django 3.2.10 on 2021-12-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211226_1621'),
        ('accounting', '0001_initial'),
        ('appointment', '0002_alter_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentt', to='accounting.payment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.doctorspecialty'),
            preserve_default=False,
        ),
    ]
