PROFILE_PHOTO_DIRECTORY = "profile_photo"
DOCTOR_IDENTIFICATION_PHOTO_DIRECTORY = "doctor_identification_photo"
DOCTOR_EDUCATION_PHOTO_DIRECTORY = "doctor_education_photo"
DOCTOR_LICENSE_FILE_DIRECTORY = "doctor_license_file"
PATIENT_IDENTIFICATION_PHOTO_DIRECTORY = "patient_identification_photo"


# Available care for doctor registration

available_care = [
    "Allergy Specialist",
    "Andrology",
    "Anesthesiologist/Chronic Pain Specialist",
    "Anesthesiology",
    "Audiology",
    "Ayurveda Specialist",
    "Bariatric Surgery",
    "Cardiology",
    "Cardiothoracic Surgery",
    "Child Health",
    "Childbirth Educator",
    "Chiropractor",
    "Clinical Genetics",
    "Community Medicine",
    "Cosmetology",
    "Critical Care Physician",
    "Dentistry",
    "Dermatology",
    "Diabetology",
    "Dietician",
    "Endocrinology",
    "Endodontist",
    "Family Physician",
    "Fetal Medicine",
    "Fitness Expert",
    "Forensic Medicine",
    "General Medicine",
    "General Practitioner",
    "General Surgery",
    "Geriatrics",
    "Hair Transplant Surgeon",
    "Hematology",
    "HIV/AIDS Specialist",
    "Homeopathy",
    "Human Anatomy Specialist",
    "Infectious Diseases",
    "Infertility",
    "Integrative Medicine",
    "Internal Medicine",
    "Interventional Radiology",
    "Lactation Counselor",
    "Maxillofacial Prosthodontist",
    "Medical Gastroenterology",
    "Medical Oncologist",
    "Medical Oncology",
    "Metabolic Surgery",
    "Microbiology",
    "Naturopathy",
    "Nephrology",
    "Neuro Surgery",
    "Neurology",
    "Nuclear Medicine",
    "Nutritionist",
    "Obstetrics And Gynaecology",
    "Occupational Therapy",
    "Ophthalmology (Eye Care)",
    "Oral And Maxillofacial Surgery",
    "Oral Implantologist",
    "Orthodontist",
    "Orthopedics And Traumatology",
    "Osteopathy Specialist",
    "Otolaryngology (E.N.T)",
    "Paediatric Dentistry",
    "Paediatric Surgery",
    "Paediatrics",
    "Pain Medicine",
    "Pathology",
    "Pediatric Allergy/Asthma Specialist",
    "Pediatric Cardiology",
    "Periodontist",
    "Pharmacology",
    "Physiotherapy",
    "Plastic Surgery – Reconstructive And Cosmetic",
    "Preventive Medicine",
    "Psychiatry",
    "Psychologist/ Counsellor",
    "Psychotherapy",
    "Pulmonology (Asthma Doctors)",
    "Radiation Oncologist",
    "Radiation Oncology",
    "Radiodiagnosis",
    "Radiology",
    "Radiotherapy",
    "Rheumatology",
    "Sexology",
    "Siddha Medicine",
    "Sleep Medicine",
    "Sonologist",
    "Speech Therapist",
    "Spine Health",
    "Spine Surgery",
    "Stem Cell Therapy",
    "Surgeon",
    "Surgical Gastroenterology",
    "Surgical Oncology",
    "Test Cancer Type",
    "Toxicology",
    "Unani Medicine",
    "Urology",
    "Vascular Surgery",
    "Venereology",
    "Wellness Medicine",
    "Yoga",
]
