PROFILE_PHOTO_DIRECTORY = "profile_photo"
DOCTOR_IDENTIFICATION_PHOTO_DIRECTORY = "doctor_identification_photo"
DOCTOR_EDUCATION_PHOTO_DIRECTORY = "doctor_education_photo"
DOCTOR_LICENSE_FILE_DIRECTORY = "doctor_license_file"
PATIENT_IDENTIFICATION_PHOTO_DIRECTORY = "patient_identification_photo"
