# Generated by Django 3.2.7 on 2021-12-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twilio_chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitingroom",
            name="room_media_mime_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
