# Generated by Django 3.2.7 on 2021-12-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twilio_chat", "0002_waitingroom_room_media_mime_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waitingroom",
            name="room_media_mime_type",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
