# Generated by Django 3.2.10 on 2022-01-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_chat', '0003_alter_waitingroom_room_media_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingroom',
            name='text',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
