# Generated by Django 3.2.7 on 2021-12-26 06:18

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0009_patientencounters_timing'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletpayout',
            name='gateway_ref',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='walletpayout',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('S', 'success'), ('F', 'failed')], default='P', max_length=2),
        ),
        migrations.CreateModel(
            name='WalletIncomingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount_charged', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'pending'), ('S', 'success'), ('F', 'failed')], default='P', max_length=2)),
                ('ehr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.patientencounters')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='wallet.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
