# Generated by Django 3.2.7 on 2021-12-26 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0009_patientencounters_timing'),
        ('wallet', '0002_auto_20211226_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletincomingpayment',
            name='ehr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.patientencounters'),
        ),
    ]
