# Generated by Django 3.2.7 on 2021-11-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="display_id",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
