# Generated by Django 3.2.7 on 2021-10-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="city"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="is verified"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="state"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="street",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="street"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="zip code"
            ),
        ),
    ]
