# Generated by Django 3.2.7 on 2021-12-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_patientinfo_display_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorinfo",
            name="profession",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
