# Generated by Django 3.2.7 on 2021-10-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_userlanguage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="email"
            ),
        ),
    ]
