# Generated by Django 3.2.7 on 2021-12-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_doctoracceptedinsurance"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorinfo",
            name="license_expiration",
            field=models.DateField(blank=True, null=True),
        ),
    ]
