# Generated by Django 3.2.7 on 2021-12-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_doctorinfo_license_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicinfo",
            name="notification_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="notification_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="pharmacyinfo",
            name="notification_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
