# Generated by Django 3.2.7 on 2021-12-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211217_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicinfo',
            name='subscription_type',
            field=models.CharField(choices=[('M', 'membership'), ('P', 'pay as you go')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='subscription_type',
            field=models.CharField(choices=[('M', 'membership'), ('P', 'pay as you go')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='pharmacyinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacyinfo',
            name='subscription_type',
            field=models.CharField(choices=[('M', 'membership'), ('P', 'pay as you go')], default='P', max_length=1),
        ),
    ]
