# Generated by Django 3.2.7 on 2021-12-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_auto_20211217_1755"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicinfo",
            name="website",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
