# Generated by Django 3.2.7 on 2021-10-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_doctorinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorinfo",
            name="gender",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
