# Generated by Django 3.2.7 on 2021-12-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20211227_1605'),
        ('user', '0008_auto_20211222_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicinfo',
            name='current_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.subscriptionhistory'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='current_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.subscriptionhistory'),
        ),
        migrations.AddField(
            model_name='pharmacyinfo',
            name='current_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.subscriptionhistory'),
        ),
    ]
