# Generated by Django 3.2.7 on 2021-12-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_auto_20211223_0843"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacyinfo",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
