# Generated by Django 3.2.10 on 2021-12-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20211223_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorspecialty',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorspecialty',
            name='specialty',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
