# Generated by Django 3.2.10 on 2022-01-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211226_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspecialty',
            name='price',
            field=models.IntegerField(help_text='Input amount in cents'),
        ),
    ]
