# Generated by Django 3.2.7 on 2021-12-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_pharmacyinfo_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacyinfo",
            name="website",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
