# Generated by Django 3.2.7 on 2021-12-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_pharmacyinfo_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacyinfo",
            name="_license_file",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="pharmacy_license_file"
            ),
        ),
        migrations.AddField(
            model_name="pharmacyinfo",
            name="license_expiration",
            field=models.DateField(blank=True, null=True),
        ),
    ]
