# Generated by Django 3.2.7 on 2022-01-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20211227_1605'),
    ]

    operations = [
    ]
