# Generated by Django 3.2.7 on 2021-10-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_auto_20211017_1829"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "admin"),
                    ("DOCTOR", "doctor"),
                    ("PATIENT", "patient"),
                    ("PHARMACY", "pharmacy"),
                    ("HOSPITAL", "hospital"),
                ],
                default="PATIENT",
                max_length=20,
                verbose_name="user type",
            ),
        ),
    ]
