# Generated by Django 3.2.7 on 2021-12-28 20:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_pharmacyservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="PharmacyAvailableHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "day_of_week",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUN", "sunday"),
                            ("MON", "monday"),
                            ("TUE", "tuesday"),
                            ("WED", "wednesday"),
                            ("THU", "thursday"),
                            ("FRI", "friday"),
                            ("SAT", "saturday"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "pharmacy_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.pharmacyinfo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
