# Generated by Django 3.2.7 on 2021-10-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorinfo",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "male"), ("FEMALE", "female"), ("OTHER", "other")],
                max_length=7,
                null=True,
            ),
        ),
    ]
