# Generated by Django 3.2.7 on 2021-10-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_doctorinfo_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorinfo",
            name="identification_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="doctorinfo",
            name="identification_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="identification_photo"
            ),
        ),
        migrations.AddField(
            model_name="doctorinfo",
            name="identification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASSPORT", "passport"),
                    ("DRIVER'S LICENSE", "driver's license"),
                    ("STATE ID", "state id"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
