# Generated by Django 3.2.7 on 2021-10-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_doctoreducation"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorinfo",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorinfo",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorinfo",
            name="professional_bio",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="doctorinfo",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
