# Generated by Django 3.2.7 on 2021-12-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_auto_20211229_0421"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DoctorSpecialty",
        ),
    ]
