# Generated by Django 3.2.7 on 2021-12-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_doctorservice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorinfo",
            name="profession",
        ),
    ]
