# Generated by Django 3.2.7 on 2022-01-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_remove_doctorinfo_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorinfo",
            name="affiliated_hospital",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.clinicinfo",
            ),
        ),
    ]
