# Generated by Django 3.2.7 on 2022-01-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_merge_20220105_0606'),
        ('user', '0019_remove_doctorinfo_profession'),
    ]

    operations = [
    ]
