# Generated by Django 3.2.7 on 2021-10-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_collectiveinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "admin"),
                    ("DOCTOR", "doctor"),
                    ("PATIENT", "patient"),
                    ("PHARMACY", "pharmacy"),
                    ("COLLECTIVE", "collective"),
                ],
                default="PATIENT",
                max_length=20,
                verbose_name="user type",
            ),
        ),
    ]
