# Generated by Django 3.2.10 on 2022-01-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_doctorinfo_affiliated_hospital'),
        ('user', '0020_merge_20220105_1539'),
    ]

    operations = [
    ]
