# Generated by Django 3.2.10 on 2022-01-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_merge_20220111_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailablehours',
            name='interval',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
