# Generated by Django 3.2.10 on 2022-01-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_doctoravailablehours_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_disabled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is disabled'),
        ),
    ]
