# Generated by Django 3.2.7 on 2021-10-23 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_auto_20211023_1317"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientInfo",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "male"),
                            ("FEMALE", "female"),
                            ("OTHER", "other"),
                        ],
                        max_length=7,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "social_security_number",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "identification_type",
                    models.CharField(
                        choices=[
                            ("PASSPORT", "passport"),
                            ("DRIVER'S LICENSE", "driver's license"),
                            ("STATE ID", "state id"),
                            ("STUDENT ID", "student id"),
                        ],
                        max_length=20,
                    ),
                ),
                ("identification_number", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "insurance_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "insurance_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "insurance_policy_holder_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("SELF PAID", "self paid"),
                            ("INSURANCE VERIFIED", "insurance verified"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "referring_doctor_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "referring_doctor_full_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "referring_doctor_phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
