# Generated by Django 3.2.10 on 2022-01-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicinfo',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyinfo',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
