# Generated by Django 3.2.7 on 2021-10-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_patientinfo_squashed_0025_auto_20211023_1407"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinfo",
            name="insurance_type",
            field=models.CharField(
                choices=[
                    ("SELF PAID", "self paid"),
                    ("INSURANCE VERIFIED", "insurance verified"),
                ],
                max_length=20,
            ),
        ),
    ]
