# Generated by Django 3.2.7 on 2021-10-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_patientinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="insurance_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="insurance_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="insurance_policy_holder_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="insurance_type",
            field=models.CharField(
                choices=[
                    ("SELF PAID", "self paid"),
                    ("INSURANCE VERIFIED", "insurance verified"),
                ],
                default=None,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="referring_doctor_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="referring_doctor_full_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="referring_doctor_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
