# Generated by Django 3.2.7 on 2021-10-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0026_doctoravailablehours_doctorreview"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CollectiveInfo",
            new_name="ClinicInfo",
        ),
        migrations.RenameField(
            model_name="clinicinfo",
            old_name="collective_type",
            new_name="clinic_type",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "admin"),
                    ("DOCTOR", "doctor"),
                    ("PATIENT", "patient"),
                    ("PHARMACY", "pharmacy"),
                    ("CLINIC", "clinic"),
                ],
                default="PATIENT",
                max_length=20,
                verbose_name="user type",
            ),
        ),
    ]
