# Generated by Django 3.2.7 on 2021-10-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0028_auto_20211030_1847"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorinfo",
            name="identification_number",
        ),
    ]
