# Generated by Django 3.2.7 on 2021-11-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0029_auto_20211030_1948"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientinfo",
            name="username",
        ),
    ]
