# Generated by Django 3.2.7 on 2021-11-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0031_alter_doctorinfo_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorinfo",
            name="identification_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
