# Generated by Django 3.2.7 on 2021-11-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_patientinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='awards',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
