# Generated by Django 3.2.7 on 2021-11-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0034_doctorinfo_awards"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorinfo",
            name="license_file",
            field=models.FileField(
                blank=True, null=True, upload_to="doctor_license_file"
            ),
        ),
    ]
