# Generated by Django 3.2.7 on 2021-11-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0035_doctorinfo_license_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="identification_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="patient_identification_photo"
            ),
        ),
    ]
