# Generated by Django 3.2.7 on 2021-11-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0036_patientinfo_identification_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorinfo",
            name="identification_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="doctor_identification_photo"
            ),
        ),
    ]
