# Generated by Django 3.2.7 on 2021-11-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0039_doctorinfo_accepted_insurance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
