# Generated by Django 3.2.7 on 2021-11-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0040_auto_20211108_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctoreducation",
            name="certificate",
            field=models.ImageField(
                blank=True, null=True, upload_to="doctor_education_photo"
            ),
        ),
    ]
