# Generated by Django 3.2.7 on 2021-11-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0041_auto_20211121_1511"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientinfo",
            old_name="identification_photo",
            new_name="_identification_photo",
        ),
        migrations.RemoveField(
            model_name="doctoreducation",
            name="_certificate",
        ),
    ]
