# Generated by Django 3.2.7 on 2021-11-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0041_alter_doctoreducation_certificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicinfo",
            name="clinic_type",
        ),
    ]
