# Generated by Django 3.2.7 on 2021-11-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0042_auto_20211126_0857"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientinfo",
            name="social_security_number",
        ),
    ]
