# Generated by Django 3.2.7 on 2021-11-26 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0043_remove_patientinfo_social_security_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
