# Generated by Django 3.2.7 on 2021-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0044_alter_patientinfo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="name_of_parent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="insurance_type",
            field=models.CharField(
                choices=[("SELF-PAY", "self-pay"), ("INSURANCE", "insurance")],
                max_length=20,
            ),
        ),
    ]
