# Generated by Django 3.2.7 on 2021-11-24 07:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0040_auto_20211108_1054"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientEncounters",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("visit_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "visit_reason",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("signed", models.BooleanField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.patientinfo",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.doctorinfo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalNotes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("medical_notes", models.TextField()),
                ("notes_html", models.TextField(blank=True, null=True)),
                (
                    "patient_encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ehr.patientencounters",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssessmentDiagnosis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("icd", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "snomed_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "snomed_description",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "disease_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("ACUTE", "acute"), ("CHRONIC", "chronic")],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("primary_diagnosis", models.BooleanField(blank=True, null=True)),
                ("assessment", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "patient_encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ehr.patientencounters",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
