# Generated by Django 3.2.7 on 2021-11-27 11:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ehr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientSocialHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "home_environment",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("children", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "higher_education",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sexual_orientation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gender_identity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tobacco_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tobacco_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tobacco_started_year", models.DateField(blank=True, null=True)),
                (
                    "tobacco_packs_per_day",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tobacco_start_date", models.DateField(blank=True, null=True)),
                ("tobacco_end_date", models.DateField(blank=True, null=True)),
                (
                    "tobacco_cessation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("exercise", models.CharField(blank=True, max_length=100, null=True)),
                ("drug_use", models.CharField(blank=True, max_length=100, null=True)),
                ("quit_date", models.DateField(blank=True, null=True)),
                ("seatbelts", models.CharField(blank=True, max_length=100, null=True)),
                ("exposure", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "alcohol_use",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "caffeine_use",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("etoh", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "patient_encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ehr.patientencounters",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
