# Generated by Django 3.2.7 on 2021-11-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ehr", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessmentdiagnosis",
            old_name="type",
            new_name="diagnosis_type",
        ),
    ]
