# Generated by Django 3.2.7 on 2021-12-03 21:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_auto_20211204_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICDs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code_description', models.CharField(blank=True, max_length=200, null=True)),
                ('icd_code', models.CharField(blank=True, max_length=20, null=True)),
                ('full_description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
