# Generated by Django 3.2.7 on 2021-12-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ehr", "0003_auto_20211204_0023"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICDs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("icd_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "full_description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
            ],
        ),
    ]
