# Generated by Django 3.2.7 on 2021-12-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_icds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ICDs',
        ),
    ]
