# Generated by Django 3.2.7 on 2021-12-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0005_delete_icds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICDs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_description', models.CharField(blank=True, max_length=200, null=True)),
                ('icd_code', models.CharField(blank=True, max_length=20, null=True)),
                ('full_description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
