# Generated by Django 3.2.7 on 2021-12-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ehr", "0006_rename_type_patientprocedure_procedure_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessmentdiagnosis",
            old_name="description",
            new_name="icd_description",
        ),
        migrations.RenameField(
            model_name="patientencounters",
            old_name="visit_reason",
            new_name="reason",
        ),
        migrations.RenameField(
            model_name="patientsocialhistory",
            old_name="higher_education",
            new_name="highest_education",
        ),
        migrations.AddField(
            model_name="patientsocialhistory",
            name="marital_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patientsocialhistory",
            name="children",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
