# Generated by Django 3.2.7 on 2021-12-22 19:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ehr", "0007_auto_20211210_0811"),
    ]

    operations = [
        migrations.AddField(
            model_name="chiefcomplaintsandhpi",
            name="timing",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name="Vitals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("reading_date", models.DateField(blank=True, null=True)),
                ("reading_time", models.TimeField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("bmi", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("pulse", models.FloatField(blank=True, null=True)),
                ("respiratory_rate", models.FloatField(blank=True, null=True)),
                ("o2_saturation", models.FloatField(blank=True, null=True)),
                ("pain", models.FloatField(blank=True, null=True)),
                ("blood_pressure", models.FloatField(blank=True, null=True)),
                (
                    "patient_encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ehr.patientencounters",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReviewOfSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("general", models.CharField(blank=True, max_length=512, null=True)),
                ("head", models.CharField(blank=True, max_length=512, null=True)),
                ("eyes", models.CharField(blank=True, max_length=512, null=True)),
                ("ears", models.CharField(blank=True, max_length=512, null=True)),
                ("nose", models.CharField(blank=True, max_length=512, null=True)),
                ("mouth", models.CharField(blank=True, max_length=512, null=True)),
                ("neck", models.CharField(blank=True, max_length=512, null=True)),
                ("breast", models.CharField(blank=True, max_length=512, null=True)),
                ("chest", models.CharField(blank=True, max_length=512, null=True)),
                ("heart", models.CharField(blank=True, max_length=512, null=True)),
                ("abdomen", models.CharField(blank=True, max_length=512, null=True)),
                ("gu", models.CharField(blank=True, max_length=512, null=True)),
                ("gyn", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "musculoskeletal",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("neurologic", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "psychiatric",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "patient_encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ehr.patientencounters",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PhysicalExam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "general_appearance",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("head", models.CharField(blank=True, max_length=512, null=True)),
                ("eyes", models.CharField(blank=True, max_length=512, null=True)),
                ("ears", models.CharField(blank=True, max_length=512, null=True)),
                ("nose", models.CharField(blank=True, max_length=512, null=True)),
                ("throat", models.CharField(blank=True, max_length=512, null=True)),
                ("neck", models.CharField(blank=True, max_length=512, null=True)),
                ("cardiac", models.CharField(blank=True, max_length=512, null=True)),
                ("lungs", models.CharField(blank=True, max_length=512, null=True)),
                ("abdomen", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "musculoskeletal",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("back", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "extremities",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "lower_extremities",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "neurological",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("skin", models.CharField(blank=True, max_length=512, null=True)),
                ("res", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "psychiatric",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("rectal", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "patient_encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ehr.patientencounters",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("lab_order", models.TextField(blank=True, null=True)),
                ("imaging_order", models.TextField(blank=True, null=True)),
                (
                    "patient_encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ehr.patientencounters",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
