# Generated by Django 3.2.7 on 2021-12-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ehr", "0008_auto_20211222_1908"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientencounters",
            name="timing",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
