# Generated by Django 3.2.7 on 2022-01-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('ehr', '0009_patientencounters_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientencounters',
            name='appointment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ehr_appointment', to='appointment.appointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientencounters',
            name='signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
