# Generated by Django 3.2.7 on 2022-01-05 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.IntegerField()),
                ('amount_after_charge', models.IntegerField(blank=True, null=True)),
                ('transaction_reference', models.TextField()),
                ('paid', models.BooleanField(default=False)),
                ('payment_gateway', models.CharField(max_length=100)),
                ('payment_released', models.BooleanField(default=False)),
                ('expected_release_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
