# Generated by Django 3.2.10 on 2022-01-03 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_payment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expected_release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 12, 58, 13, 7862)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 12, 58, 23, 791935)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_released',
            field=models.BooleanField(default=False),
        ),
    ]
