# Generated by Django 3.2.10 on 2022-01-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20220103_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_after_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
